name: Build Android Debug APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.36

    - name: Clean pyjnius build artifacts
      run: |
        buildozer android clean --recipe pyjnius || true

    - name: Apply pyjnius long fix patch
      run: |
        patch -p1 -d "${GITHUB_WORKSPACE}/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/pyjnius-sdl2/arm64-v8a__ndk_target_24/pyjnius" < pyjnius_long_fix.patch || true

    - name: Install p4a prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            ant \
            autoconf \
            automake \
            ccache \
            cmake \
            g++ \
            gcc \
            git \
            lbzip2 \
            libffi-dev \
            libltdl-dev \
            libtool \
            libssl-dev \
            make \
            openjdk-17-jdk \
            patch \
            pkg-config \
            python3 \
            python3-dev \
            python3-pip \
            python3-venv \
            sudo \
            unzip \
            wget \
            zip \
            lld

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Cache Android SDK
      id: cache-android-sdk
      uses: actions/cache@v4
      with:
        path: ${{ env.HOME }}/.buildozer/android/platform/android-sdk
        key: ${{ runner.os }}-android-sdk-33-ndk-25.1.8937393

    - name: Install Android SDK Build Tools and Platform Tools
      if: steps.cache-android-sdk.outputs.cache-hit != 'true'
      run: |
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        mkdir -p "$ANDROID_HOME"

        # Download and set up command-line tools
        curl -sL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://github.com/kmedya-dev/browser/releases/download/v1.0.0/commandlinetools-linux-13114758_latest.zip" -o /tmp/commandlinetools.zip
        unzip -q /tmp/commandlinetools.zip -d "$ANDROID_HOME/cmdline-tools"
        mv "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/latest"

        # Create legacy path for sdkmanager and accept licenses
        # This is the most reliable way to ensure all licenses are accepted.
        # The "Broken pipe" warning is harmless and will only appear once when the cache is being created.
        mkdir -p "$ANDROID_HOME/tools/bin"
        ln -sf "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" "$ANDROID_HOME/tools/bin/sdkmanager"
        yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_HOME" --licenses >/dev/null 2>&1 || true

        # Install SDK packages
        "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_HOME" \
          "build-tools;33.0.2" \
          "platforms;android-33" \
          "platform-tools" \
          "ndk;25.1.8937393"

    - name: Set Android Environment Variables
      run: |
        echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Install OpenSSL development libraries
      run: sudo apt-get update && sudo apt-get install -y libssl-dev

    - name: Attempt to fix libffi build (libtoolize)
      run: |
        # Navigate to the libffi source directory within the p4a build
        LIBFFI_DIR="${GITHUB_WORKSPACE}/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_24/libffi"
        if [ -d "$LIBFFI_DIR" ]; then
          echo "Attempting libtoolize --force in $LIBFFI_DIR"
          cd "$LIBFFI_DIR"
          libtoolize --force
          autoreconf --force --install
          cd "${GITHUB_WORKSPACE}"
        else
          echo "Libffi directory not found at $LIBFFI_DIR. Skipping libtoolize fix."
        fi

    - name: Install specific Autotools versions (for libffi)
      run: |
        sudo apt-get update
        sudo apt-get install -y make gcc

        # Install Autoconf 2.69
        curl -sL http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz | tar xz
        cd autoconf-2.69
        ./configure
        make
        sudo make install
        cd ..

        # Install Libtool 2.4.6
        curl -sL http://ftp.gnu.org/gnu/libtool/libtool-2.4.6.tar.gz | tar xz
        cd libtool-2.4.6
        ./configure
        make
        sudo make install
        cd ..

    - name: Trigger SDK setup
      run: |
        buildozer android debug || true

    - name: Check if .buildozer directory exists
      run: |
        echo " Checking for .buildozer directory..."
        if [ -d .buildozer ]; then
          echo "✅ .buildozer directory found!"
          echo " Contents:"
          ls -la .buildozer
        else
          echo "❌ ERROR: .buildozer directory NOT found!"
          echo " Possible fix: Run 'buildozer android debug' locally to generate it."
          exit 1
        fi

    - name: Build with Buildozer
      run: |
        mkdir -p logs
        buildozer -v android debug | tee logs/buildozer-output.log

    - name: Upload APK Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: webview-app-debug-apk
        path: bin/*.apk

    - name: Upload Build Log Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: buildozer-log
        path: .buildozer/buildozer.log

    - name: Upload Terminal Output Log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: buildozer-output-log
        path: logs/buildozer-output.log
